# 金币奖励
kill-zombie-coins: 50
kill-zombie-main-coins: 150
infect-human-coins: 50
survive-human-coins: 200
# 人类胜利时排行榜奖励（前3名，单位硬币）
rank-reward-coins: [200, 150, 100]

# 经验值
headshot-xp: 5
kill-zombie-xp: 10
kill-zombie-main-xp: 30
infect-human-xp: 20
pass-door-xp: 5
human-win-xp: 100
participate-xp: 50
